layout_spectrum: 0.05252453149296343
typography_spectrum: 0.4065033169463277
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.43828641390427947
  lightness: 0.18573247641324997
  saturation: 0.8321301119867712
  rhythmicContrast: 0.22523424960672855
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Canines of New York
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Canines of New York
description: Somebody New
purpose: []
