typography_spectrum: 0.07850784412585199
color:
  brandColors:
    - '#FF5335'
    - '#B39C85'
    - '#306E73'
    - '#3B424D'
    - '#1D181F'
  brandStrength: 0.5904894019477069
  lightness: 0.4592870734632015
  saturation: 0.8779316663276404
  rhythmicContrast: 0.198620252776891
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.43195711611770093
analytics:
  google: null
  facebook: null
  twitter: null
name: Canines of New York
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Our Dogs
    id: eb232f56-2635-400a-abd9-ee77fba65d07
    type: content
  - name: When the Dog Decides Where You Live
    id: 8ec01e14-8e0e-46e4-83db-226b5e6a5fc8
    type: content
favicon: null
title: Canines of New York
description: Somebody New
purpose: []
